spring.docker.compose.enabled=false
#spring.docker.compose.file=docker-compose-prod.yml

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database=mysql

spring.h2.console.enabled=false

# MySql DB
spring.datasource.url=jdbc:mysql://10.0.0.2:3306/lighterim?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
spring.datasource.username=lighter_im
spring.datasource.password=!HDXfJgcvMRehHd1
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
nostr.relay.pubkey=b895aa96ee5c6aa54783cb76047ea6c375089953b1b37cba3ca0aaa090a5e48f
notice.lighter.im.pubkey=cae467c0e1c6b1fdc3a9d219cc09ef858ea0da61cc24b63cd1b4e78188845a59
