type OwnershipTransferred @entity(immutable: true) {
  id: Bytes!
  previousOwner: Bytes! # address
  newOwner: Bytes! # address
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type QuotaUpgraded @entity(immutable: true) {
  id: Bytes!
  renter: Bytes! # address
  tokenId: BigInt! # uint256
  tbaAddress: Bytes! # address
  hexNostrPubKey: String! # string
  rent: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type RentPriceUpdated @entity(immutable: true) {
  id: Bytes!
  oldPrice: BigInt! # uint256
  newPrice: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type TicketDestroyed @entity(immutable: true) {
  id: Bytes!
  recipient: Bytes! # address
  tokenId: BigInt! # uint256
  tbaAddress: Bytes! # address
  hexNostrPubKey: String! # string
  amount: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type TicketRentedWithTBA @entity(immutable: true) {
  id: Bytes!
  renter: Bytes! # address
  tokenId: BigInt! # uint256
  tbaAddress: Bytes! # address
  nostrPubKey: Bytes! # bytes32
  rent: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}
